
parameters:
- name: Hostpoolname
  type: string
  default: "null"
- name: ResourceGroup
  type: string
  default: "null"
- name: MSIXPackagePath
  type: string
  default: "null"
- name: DisplayName
  type: string
  default: "null"

  
trigger: none

steps:
- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script: FilePath'
  inputs:
    azureSubscription: 'azure-prod-service-connection'  #Provide right azure subscription name here
    ScriptPath: 'MSIXAppAttach_v01.ps1'
    ScriptArguments: "-Hostpoolname ${{parameters.Hostpoolname}} `
                      -ResourceGroup ${{parameters.ResourceGroup}} `
                      -MSIXPackagePath ${{parameters.MSIXPackagePath}} `
                      -DisplayName ${{parameters.DisplayName}} ""
                                                                        
    azurePowerShellVersion: LatestVersion