

parameters:
- name: Hostpoolname
  type: string
  default: "null"
- name: ResourceGroup
  type: string
  default: "null"
- name: MSIXPackageName (ex:"NotepadPlus_8.4.6.0_x64__70w54f1edgcma")
  type: string
  default: "null"
- name: AppDisplayName
  type: string
  default: "null"
- name: RemoveApplication
  type: boolean
  default: false  
- name: RemoveMSIXPackage
  type: boolean
  default: false 
- name: Active
  type: boolean
  default: false
- name: Inactive
  type: boolean
  default: false  



trigger: none

steps:
- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script: FilePath'
  inputs:
    azureSubscription: 'azure-prod-service-connection'  #Provide right azure subscription name here
    ScriptPath: 'MSIXAppAttachAdminTask.ps1'
    ScriptArguments: "-Hostpoolname ${{parameters.Hostpoolname}} `
                      -ResourceGroup ${{parameters.ResourceGroup}} `
                      -MSIXPackageName ${{parameters.MSIXPackageName}} `
                      -AppDisplayName ${{parameters.AppDisplayName}} `
                      -RemoveApplication $${{parameters.RemoveApplication}} `
                      -RemoveMSIXPackage $${{parameters.RemoveMSIXPackage}} `
                      -Active $${{parameters.Active}} `
                      -Inactive $${{parameters.Inactive}}"



    azurePowerShellVersion: LatestVersion